synonyms = {'pull': [u'pull', u'draw', u'force', u'attract', u'pull in', u'draw in', u'perpetrate', u'commit', u'pull out',
          u'get out', u'take out', u'overstretch', u'rend', u'rip', u'rive', u'pluck', u'tear', u'deplume',
          u'deplumate', u'displume', u'extract', u'pull up', u'draw out', u'act', u'back', u'bust', u'displace',
          u'drive', u'endorse', u'hit', u'indorse', u'injure', u'move', u'plump for', u'plunk for', u'rein', u'rein in',
          u'remove', u'root', u'row', u'rupture', u'side', u'snap', u'strip', u'support', u'take away',
          u'withdraw', u'wound'],
 'hit': [u'strike', u'impinge on', u'run into', u'collide with', u'reach', u'make', u'attain', u'arrive at', u'gain',
         u'shoot', u'pip', u'stumble', u'score', u'tally', u'rack up', u'come to', u'murder', u'slay', u'dispatch',
         u'bump off', u'off', u'polish off', u'remove', u'advance', u'affect', u'approach', u'arrive', u'assail',
         u'attack', u'bear on', u'bear upon', u'bring home the bacon', u'come', u'come by', u'come through',
         u'deliver the goods', u'displace', u'gain ground', u'get', u'get ahead', u'have', u'impact', u'impel',
         u'injure', u'kill', u'make headway', u'move', u'propel', u'pull ahead', u'succeed',
         u'take in', u'touch', u'touch on', u'win', u'wound'],
 'consume': [u'drink', u'devour', u'go through', u'ingest', u'take in',  u'have', u'squander', u'waste', u'ware',
             u'eat up', u'use up', u'eat', u'deplete', u'exhaust', u'run through', u'wipe out', u'absorb', u'destroy',
            u'engage', u'engross', u'expend', u'occupy', u'ruin', u'spend'],
 'drop': [u'sink', u'drop down', u'knock off', u'drop off', u'set down', u'put down', u'unload', u'discharge', u'fell',
          u'strike down', u'spend', u'expend', u'flatten', u'dangle', u'swing', u'dismiss',
          u'send packing', u'send away', u'dribble', u'drip', u'shed', u'cast', u'cast off', u'shake off', u'throw',
          u'throw off', u'throw away', u'neglect', u'pretermit', u'omit', u'miss', u'leave out', u'overlook',
          u'overleap', u'devolve', u'deteriorate', u'degenerate', u'alter', u'bear', u'birth', u'can', u'cease',
          u'change', u'change posture', u'come down', u'decline', u'deliver', u'descend', u'discontinue',
          u'displace', u'express', u'fall', u'fire', u'force out', u'give birth', u'give notice', u'give the axe',
          u'give the sack', u'give tongue to', u'give up', u'go down', u'hang', u'have', u'lay off', u'lose', u'modify',
          u'move', u'pay', u'pour', u'quit', u'remove', u'sack', u'stop', u'take away', u'terminate', u'utter',
          u'verbalise', u'verbalize', u'wane', u'withdraw', u'worsen'],
 'lift': [u'raise', u'lift', u'elevate', u'get up', u'bring up', u'rise', u'arise', u'move up', u'go up', u'come up',
          u'uprise', u'revoke', u'annul', u'countermand', u'reverse', u'repeal', u'overturn', u'rescind', u'vacate',
          u'pilfer', u'cabbage', u'purloin', u'pinch', u'abstract', u'snarf', u'swipe', u'hook', u'sneak', u'filch',
          u'nobble', u'hoist', u'wind', u'rear', u'plagiarize', u'plagiarise', u'rustle', u'airlift', u'face-lift',
          u'alter', u'ameliorate', u'amend', u'appear', u'better', u'buckle', u'call', u'cancel', u'change', u'dig',
          u'dig out', u'displace', u'emit', u'end', u'fly', u'go', u'heave', u'improve', u'let loose', u'let out',
          u'liquidate', u'locomote', u'meliorate', u'modify', u'move', u'operate', u'operate on', u'pay off',
          u'remove', u'scalp', u'seem', u'send for', u'steal', u'strike down', u'take away', u'terminate',
          u'travel', u'utter', u'warp', u'withdraw'],
 'push': [u'push', u'force', u'bear on', u'advertise', u'advertize', u'promote', u'tug', u'labor', u'labour', u'drive',
          u'crowd', u'crusade', u'fight', u'press', u'campaign', u'agitate', u'approach', u'come near', u'come on',
          u'deal', u'displace', u'draw close', u'draw near', u'exhort', u'go', u'go up', u'locomote', u'move', u'near',
          u'praise', u'sell', u'struggle', u'trade', u'travel', u'urge', u'urge on'],
 'close': [u'shut', u'close up', u'fold', u'shut down', u'close down', u'conclude', u'come together', u'fill up',
           u'approach', u'bar', u'barricade', u'block', u'block off', u'block up', u'blockade', u'bring together',
           u'cease', u'change state', u'come near', u'come on', u'complete', u'draw close', u'draw near', u'end',
           u'engage', u'fill', u'finish', u'go up', u'join', u'move', u'near', u'prosecute', u'pursue', u'stop',
           u'terminate', u'trade', u'turn'],
 'open': [u'open up', u'cut open', u'cut', u'unfold', u'spread', u'spread out', u'afford', u'give', u'arise', u'change state', u'come up',
          u'commence', u'display', u'embark on', u'exhibit', u'expose', u'move', u'start', u'start up', u'turn',
          u'undo', u'yield'],
 'turn off': [u'switch off', u'turn out', u'put off', u'flip', u'repel', u'repulse', u'switch', u'throw',
              u'turn'],
 'turn on': [u'switch on', u'depend on', u'devolve on', u'depend upon', u'ride', u'hinge on', u'hinge upon', u'agitate',
             u'rouse', u'charge', u'commove', u'excite', u'charge up', u'arouse', u'sex', u'wind up', u'trip',
             u'trip out', u'get off', u'bring forth', u'change', u'disturb', u'flip', u'produce', u'shake', u'shake up',
             u'stimulate', u'stir', u'switch', u'throw', u'trouble', u'upset', u'use', u'start'],
'turnoff': [u'switch off', u'turn out', u'put off', u'flip', u'repel', u'repulse', u'switch',
                         u'throw',
                         u'turn'],
'turnon': [u'switch on', u'depend on', u'devolve on', u'depend upon', u'ride', u'hinge on', u'hinge upon',
                        u'agitate',
                        u'rouse', u'charge', u'commove', u'excite', u'charge up', u'arouse', u'sex', u'wind up',
                        u'trip',
                        u'trip out', u'get off', u'bring forth', u'change', u'disturb', u'flip', u'produce', u'shake',
                        u'shake up',
                        u'stimulate', u'stir', u'switch', u'throw', u'trouble', u'upset', u'use', u'start']
            }
